PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE status(id_status integer primary key, label_status varchar(150));
INSERT INTO "status" VALUES(1,'Adult');
INSERT INTO "status" VALUES(2,'Child');
CREATE TABLE category (id_category integer primary key autoincrement, label_category varchar(150));
CREATE TABLE pik_user(id_pik_user integer primary key autoincrement, fname_pik_user varchar(150), name_pik_user varchar(150), age_pik_user integer, category_pik_user integer, id_status integer, foreign key(id_status) references status (id_status));
INSERT INTO "pik_user" VALUES(1,'Amine','Ahmed-Ali',24,1,1);
INSERT INTO "pik_user" VALUES(2,'Brandon','Quinne',14,1,2);
INSERT INTO "pik_user" VALUES(3,'Morgan','Bouvet',16,1,2);
INSERT INTO "pik_user" VALUES(4,'Vincent','Grateau',17,1,1);
INSERT INTO "pik_user" VALUES(5,'Marwan','Burelle',39,1,1);
CREATE TABLE level(id_level integer primary key autoincrement, label_level varchar(150), speed_exp_level float, score_exp_level integer, text_level varchar(500));
CREATE TABLE results (id_res integer primary key autoincrement, score integer, id_pik_user integer, id_level integer, foreign key (id_pik_user) references pik_user(id_pik_user), foreign key (id_level) references level(id_level));
INSERT INTO "results" VALUES(1,360,1,2);
INSERT INTO "results" VALUES(2,300,1,3);
INSERT INTO "results" VALUES(3,302,2,1);
INSERT INTO "results" VALUES(4,302,3,4);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('pik_user',5);
INSERT INTO "sqlite_sequence" VALUES('results',4);
CREATE VIEW stats as select * from results where id_user = 1;
CREATE VIEW stats_v as select * from results where id_pik_user = 1;
COMMIT;
